### ISSUE TITLE
header anchors are truncated

### ISSUE THREAD

**Issue by ghost** [Synthetica9/pandoc-formatters#1]
Thanks for sharing this @Synthetica9!

I tried in on the [rust.section.md](https://github.com/NixOS/nixpkgs/blob/2a139eae7f4932e846d0b0f505efee78d81f82e1/doc/languages-frameworks/rust.section.md) from nixpkgs and saw that `main.py` stripped header anchors.
I ran `main.py` against rust.section.md and then did a diff between that and the redirected output:
```
< ### Declarative Rust overlay installation {#declarative-rust-overlay-installation}
---
> ### Declarative Rust overlay installation
964,965c987,989
```

**Comment by Synthetica9** [comment]
My first guess is that this happens when the specified header anchor is the same as pandoc would've implicitly generated. Maybe there's a flag to force pandoc to always output these "implicit" anchors?

**Comment by ghost** [comment]
> Maybe there's a flag to force pandoc to always output these "implicit" anchors?

Good question.

On an unrelated note, It makes me wonder *why* the Rust language section guide has manually specified headers.

From what I researched, https://github.com/NixOS/nixpkgs/commit/6ecc641d087df8b8896ebd876bba592e981877c9 introduced manually specified header anchors.
That was to normalize differences between pandoc's default markdown parsing and the common mark mode (specifically  the `auto_identifiers` [extension](https://pandoc.org/MANUAL.html#headings-and-sections))

**Comment by Synthetica9** [comment]
(gonna close this because it's not an issue with the filter but with "how do I invoke pandoc to do the thing I want", but feel free to keep posting here)
